[[headers]]
for = "bower_components/components-font-awesome/webfonts/*.woff"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "application/font-woff"

[[headers]]
for = "bower_components/components-font-awesome/webfonts/*.ttf"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "application/font-ttf"